name: Build and Release

on:
  # Trigger on manual dispatch
  workflow_dispatch

permissions:
  contents: write


jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Tag
        uses: tschm/cradle/actions/tag@v0.1.58
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
